from typing import Protocol, Optional


class UserRepository(Protocol):
    def get_by_id(self, user_id: str, fields: str = "*") -> Optional[dict]: ...
    def get_by_username(self, username: str) -> Optional[dict]: ...
    def get_many_by_ids(self, user_ids: list[str], fields: str = "*") -> list[dict]: ...
    def create(self, data: dict) -> dict: ...
    def upsert(self, data: dict) -> dict: ...
    def update(self, user_id: str, data: dict) -> Optional[dict]: ...
    def check_username_available(self, username: str) -> bool: ...
    def ensure_exists(self, user_id: str, auth_service) -> None:
        """Auto-create user row if missing (syncs auth user to users table)."""
        ...
    def search(self, query: str, limit: int = 20) -> list[dict]: ...


class WorkExperienceRepository(Protocol):
    def get_by_user(self, user_id: str) -> list[dict]: ...
    def get_owner(self, experience_id: str) -> Optional[str]: ...
    def create(self, data: dict) -> dict: ...
    def update(self, experience_id: str, data: dict) -> Optional[dict]: ...
    def delete(self, experience_id: str) -> None: ...


class EducationRepository(Protocol):
    def get_by_user(self, user_id: str) -> list[dict]: ...
    def get_owner(self, education_id: str) -> Optional[str]: ...
    def create(self, data: dict) -> dict: ...
    def update(self, education_id: str, data: dict) -> Optional[dict]: ...
    def delete(self, education_id: str) -> None: ...


class SkillRepository(Protocol):
    def get_by_user(self, user_id: str) -> list[dict]: ...
    def get_owner(self, skill_id: str) -> Optional[str]: ...
    def create(self, data: dict) -> dict: ...
    def delete(self, skill_id: str) -> None: ...


class LoginActivityRepository(Protocol):
    def track(self, data: dict) -> None: ...
    def deactivate_session(self, session_id: str) -> None: ...


class FollowRepository(Protocol):
    def follow(self, follower_id: str, following_id: str) -> None: ...
    def unfollow(self, follower_id: str, following_id: str) -> None: ...
    def is_following(self, follower_id: str, following_id: str) -> bool: ...
    def get_following_ids(self, user_id: str, limit: int, offset: int) -> list[str]: ...
    def get_follower_ids(self, user_id: str, limit: int, offset: int) -> list[str]: ...


class NotificationRepository(Protocol):
    def get_for_user(self, user_id: str, unread_only: bool,
                     limit: int, offset: int) -> list[dict]: ...
    def count_unread(self, user_id: str) -> int: ...
    def get_owner(self, notification_id: str) -> Optional[str]: ...
    def mark_read(self, notification_id: str) -> None: ...
    def mark_all_read(self, user_id: str) -> None: ...
    def create(self, data: dict) -> None: ...
    def delete(self, notification_id: str) -> None: ...
    def clear_read(self, user_id: str) -> None: ...


class ReportRepository(Protocol):
    def create(self, data: dict) -> dict: ...
    def get_existing(self, reporter_id: str, target_type: str,
                     target_id: str) -> Optional[dict]: ...
    def get_by_reporter(self, reporter_id: str, limit: int,
                        offset: int) -> list[dict]: ...
    def get_queue(self, status: str, limit: int, offset: int) -> list[dict]: ...
    def update_status(self, report_id: str, data: dict) -> Optional[dict]: ...
    def target_exists(self, target_type: str, target_id: str) -> bool: ...
    def get_user_profile(self, user_id: str) -> Optional[dict]: ...


class ConnectionRepository(Protocol):
    def get_by_id(self, connection_id: str) -> Optional[dict]: ...
    def get_between(self, user1_id: str, user2_id: str) -> Optional[dict]: ...
    def get_for_user(self, user_id: str, status: str,
                     limit: int, offset: int) -> list[dict]: ...
    def get_pending_received(self, user_id: str, limit: int,
                             offset: int) -> list[dict]: ...
    def get_pending_sent(self, user_id: str, limit: int,
                         offset: int) -> list[dict]: ...
    def create(self, data: dict) -> dict: ...
    def update(self, connection_id: str, data: dict) -> Optional[dict]: ...
    def delete(self, connection_id: str) -> None: ...
    def get_connected_ids(self, user_id: str) -> list[str]: ...
    def is_blocked(self, blocker_id: str, blocked_id: str) -> bool: ...
    def count_accepted(self, user_id: str) -> int: ...
    def get_suggestions(self, user_id: str, exclude_ids: list[str],
                        limit: int) -> list[dict]: ...


class SaveRepository(Protocol):
    def create_folder(self, data: dict) -> dict: ...
    def get_folders(self, user_id: str) -> list[dict]: ...
    def get_folder(self, folder_id: str, user_id: str) -> Optional[dict]: ...
    def update_folder(self, folder_id: str, user_id: str,
                      data: dict) -> Optional[dict]: ...
    def delete_folder(self, folder_id: str, user_id: str) -> None: ...
    def get_folder_post_counts(self, user_id: str,
                               folder_ids: list[str]) -> dict[str, int]: ...
    def save_post(self, user_id: str, post_id: str,
                  folder_id: Optional[str] = None) -> None: ...
    def unsave_post(self, user_id: str, post_id: str) -> None: ...
    def get_saved_post_ids(self, user_id: str, limit: int,
                           offset: int) -> list[str]: ...
    def get_unsorted_post_ids(self, user_id: str, limit: int,
                              offset: int) -> list[str]: ...
    def get_folder_post_ids(self, folder_id: str, user_id: str,
                            limit: int, offset: int) -> list[str]: ...
    def search_saved(self, user_id: str, query: str,
                     limit: int) -> list[str]: ...


class PostRepository(Protocol):
    def get_by_id(self, post_id: str) -> Optional[dict]: ...
    def get_feed(self, visibility: str, limit: int, offset: int) -> list[dict]: ...
    def get_by_author_ids(self, author_ids: list[str],
                          limit: int, offset: int) -> list[dict]: ...
    def get_by_author(self, author_id: str, limit: int,
                      offset: int) -> list[dict]: ...
    def get_by_ids(self, post_ids: list[str]) -> list[dict]: ...
    def create(self, data: dict) -> dict: ...
    def update(self, post_id: str, data: dict) -> Optional[dict]: ...
    def delete(self, post_id: str) -> None: ...
    def get_owner(self, post_id: str) -> Optional[str]: ...
    def search(self, query: str, limit: int = 20) -> list[dict]: ...
    def get_trending(self, days: int, limit: int) -> list[dict]: ...

    # Engagement
    def add_like(self, post_id: str, user_id: str) -> None: ...
    def remove_like(self, post_id: str, user_id: str) -> None: ...
    def count_likes(self, post_id: str) -> int: ...
    def update_like_count(self, post_id: str, count: int) -> None: ...
    def add_repost(self, post_id: str, user_id: str) -> None: ...
    def remove_repost(self, post_id: str, user_id: str) -> None: ...
    def increment_reposts(self, post_id: str) -> None: ...
    def decrement_reposts(self, post_id: str) -> None: ...
    def add_save(self, post_id: str, user_id: str) -> None: ...
    def remove_save(self, post_id: str, user_id: str) -> None: ...

    # Batch engagement (for bulk_enrich)
    def get_liked_post_ids(self, user_id: str,
                           post_ids: list[str]) -> set[str]: ...
    def get_reposted_post_ids(self, user_id: str,
                              post_ids: list[str]) -> set[str]: ...
    def get_saved_post_ids(self, user_id: str,
                           post_ids: list[str]) -> set[str]: ...
    def get_like_counts(self, post_ids: list[str]) -> dict[str, int]: ...

    # Media
    def get_media(self, post_id: str) -> list[dict]: ...
    def get_media_bulk(self, post_ids: list[str]) -> dict[str, list[dict]]: ...
    def insert_media(self, media_list: list[dict]) -> None: ...
    def delete_media(self, post_id: str) -> None: ...

    # Polls
    def create_poll(self, data: dict) -> dict: ...
    def create_poll_options(self, options: list[dict]) -> None: ...
    def get_poll_by_post(self, post_id: str) -> Optional[dict]: ...
    def get_polls_bulk(self, post_ids: list[str]) -> dict[str, dict]: ...
    def get_poll_user_vote(self, poll_id: str, user_id: str) -> Optional[str]: ...
    def get_poll_user_votes_bulk(self, poll_ids: list[str],
                                 user_id: str) -> dict[str, str]: ...
    def upsert_poll_vote(self, poll_id: str, option_id: str,
                         user_id: str) -> Optional[str]: ...
    def increment_poll_votes(self, option_id: str) -> None: ...
    def decrement_poll_votes(self, option_id: str) -> None: ...

    # Comments
    def get_comments(self, post_id: str, limit: int,
                     offset: int) -> list[dict]: ...
    def create_comment(self, data: dict) -> dict: ...
    def get_comment_owner(self, comment_id: str) -> Optional[dict]: ...
    def update_comment(self, comment_id: str, data: dict) -> Optional[dict]: ...
    def delete_comment(self, comment_id: str) -> None: ...
    def increment_comments(self, post_id: str) -> None: ...
    def decrement_comments(self, post_id: str) -> None: ...
    def get_liked_comment_ids(self, user_id: str,
                              comment_ids: list[str]) -> set[str]: ...


class MessageRepository(Protocol):
    def get_conversation(self, conversation_id: str) -> Optional[dict]: ...
    def create_conversation(self) -> dict: ...
    def get_conversations_for_user(self, user_id: str) -> list[dict]: ...
    def delete_conversation(self, conversation_id: str) -> None: ...

    def get_participant_ids(self, conversation_id: str) -> list[str]: ...
    def add_participant(self, conversation_id: str, user_id: str) -> None: ...
    def is_participant(self, conversation_id: str, user_id: str) -> bool: ...
    def get_user_conversation_ids(self, user_id: str) -> list[str]: ...
    def toggle_pin(self, conversation_id: str, user_id: str) -> bool: ...

    def get_messages(self, conversation_id: str, limit: int,
                     offset: int) -> list[dict]: ...
    def get_message(self, message_id: str) -> Optional[dict]: ...
    def create_message(self, data: dict) -> dict: ...
    def update_message(self, message_id: str, data: dict) -> Optional[dict]: ...
    def soft_delete_message(self, message_id: str) -> None: ...
    def mark_read(self, conversation_id: str, user_id: str) -> None: ...
    def count_unread(self, conversation_id: str, user_id: str) -> int: ...
    def count_total_unread(self, user_id: str,
                           conversation_ids: list[str]) -> int: ...
    def has_reply_after(self, conversation_id: str, sender_id: str,
                        after_ts: str) -> bool: ...

    def get_reactions(self, message_ids: list[str]) -> dict[str, list[dict]]: ...
    def toggle_reaction(self, message_id: str, user_id: str,
                        emoji: str) -> str: ...
    def remove_reaction(self, message_id: str, user_id: str,
                        emoji: str) -> None: ...

    def search_messages(self, conversation_ids: list[str],
                        query: str, limit: int) -> list[dict]: ...

    def find_conversation_between(self, user_id: str,
                                  other_user_id: str) -> Optional[str]: ...
