import React from 'react';

export default function PrivacyPolicy() {
  return (
    <div style={{ backgroundColor: '#0a0e17', color: '#94a3b8', minHeight: '100vh', padding: '60px 20px', fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif', lineHeight: '1.7' }}>
      <div style={{ maxWidth: '850px', margin: '0 auto' }}>
        <h1 style={{ fontSize: '2.5rem', fontWeight: 800, marginBottom: '0.5rem', color: '#f8fafc' }}>Privacy Policy</h1>
        <div style={{ color: '#3b82f6', fontSize: '0.95rem', fontWeight: 600, marginBottom: '3rem', textTransform: 'uppercase' }}>Last Updated: June 2026</div>

        <h2 style={{ fontSize: '1.5rem', marginTop: '2.5rem', color: '#ffffff', borderBottom: '1px solid #1e293b', paddingBottom: '0.5rem' }}>Introduction</h2>
        <p>At Puteware, we believe that privacy is not a feature — it is a foundation. Mericet is built from the ground up with the principle that your data belongs to you, and our job is to be transparent stewards of the information you trust us with.</p>
        <p>This Privacy Policy explains in clear, plain language what personal data we collect, why we collect it, how we use and store it, who we share it with (and who we never share it with), and what rights you have over your own information.</p>
        <p>This Policy applies to all users of the Mericet platform, including the mobile application, web platform, desktop application, and any associated tools and services. It should be read alongside our Terms of Service.</p>
        <p>If you have any questions about this Policy, you can reach us directly at privacy@puteware.com. We are real people and we respond to every genuine inquiry.</p>

        <h2 style={{ fontSize: '1.5rem', marginTop: '2.5rem', color: '#ffffff', borderBottom: '1px solid #1e293b', paddingBottom: '0.5rem' }}>1. Who We Are</h2>
        <p>Mericet is a professional networking and knowledge platform operated by Puteware. We are headquartered in India. As the operator of this platform, Puteware acts as the data controller for personal data collected through Mericet. You can contact our team at any time using the details provided at the end of this Policy.</p>

        <h2 style={{ fontSize: '1.5rem', marginTop: '2.5rem', color: '#ffffff', borderBottom: '1px solid #1e293b', paddingBottom: '0.5rem' }}>2. Data We Collect</h2>
        <p>We collect data in three ways: information you actively give us, information generated by your activity on the platform, and limited technical information provided by your device or browser.</p>
        
        <h3 style={{ fontSize: '1.15rem', color: '#f1f5f9', marginTop: '1.5rem' }}>2.1 Account and Registration Data</h3>
        <p>When you sign up for Mericet, we collect: your full name, email address, phone number (only if you choose to provide it), date of birth (for age verification), profile photograph, username, and the method you used to register (email, GitHub, LinkedIn, Reddit, etc.).</p>

        <h3 style={{ fontSize: '1.15rem', color: '#f1f5f9', marginTop: '1.5rem' }}>2.2 Profile Data</h3>
        <p>Information you add to your profile, including your professional headline, bio, current role, work history, educational background, skills, social media links, and any other information you voluntarily enter into your profile. This also includes the private Connection Labels and Notes you assign to people in your network, which are visible only to you.</p>

        <h3 style={{ fontSize: '1.15rem', color: '#f1f5f9', marginTop: '1.5rem' }}>2.3 Verification and Proof of Work Data</h3>
        <p>If you choose to verify your identity or use the Proof of Work feature, we collect the documents you submit, including government-issued identification, offer letters, certificates, project links, and work samples. This category of data is treated with the highest level of security and access restrictions within our systems.</p>

        <h3 style={{ fontSize: '1.15rem', color: '#f1f5f9', marginTop: '1.5rem' }}>2.4 Activity and Behavioral Data</h3>
        <p>Information about how you use the platform: posts you create, content you save to Vault folders, reactions you leave, accounts you follow or unfollow, connection requests you send or receive, search queries you enter, polls you respond to, Focus Mode goals you set, collaboration opportunities you engage with, and your interaction patterns with the AI Digest and Collective Intelligence Summaries.</p>

        <h3 style={{ fontSize: '1.15rem', color: '#f1f5f9', marginTop: '1.5rem' }}>2.5 Communication Data</h3>
        <p>All direct messages sent through Mericet are end-to-end encrypted. Puteware does not have access to the content of your private conversations. We do collect metadata such as the time a message was sent and the fact that a conversation exists between two accounts — but never the content.</p>

        <h3 style={{ fontSize: '1.15rem', color: '#f1f5f9', marginTop: '1.5rem' }}>2.6 Device and Technical Data</h3>
        <p>When you access Mericet, we automatically collect certain technical information: your IP address, device type and model, operating system, browser type, app version, general location (city-level only, derived from IP address, not GPS), session duration, crash logs, and error reports. This data is used exclusively for security, debugging, and platform performance purposes.</p>

        <h3 style={{ fontSize: '1.15rem', color: '#f1f5f9', marginTop: '1.5rem' }}>2.7 Location Data (Optional)</h3>
        <p>If you use the Map feature (powered by Google Maps API) to add your location to your profile — for example, your city, workplace, or school — we collect and store that location information as part of your profile. This is entirely optional and can be removed at any time.</p>

        <h3 style={{ fontSize: '1.15rem', color: '#f1f5f9', marginTop: '1.5rem' }}>2.8 Third-Party OAuth Data</h3>
        <p>If you sign up or log in using GitHub, Reddit, or LinkedIn, we receive limited profile information from those services such as your name, email address, and profile photo. We do not receive your passwords or any data beyond what is necessary for authentication.</p>

        <h2 style={{ fontSize: '1.5rem', marginTop: '2.5rem', color: '#ffffff', borderBottom: '1px solid #1e293b', paddingBottom: '0.5rem' }}>3. How We Use Your Data</h2>
        <p>We use the data we collect for specific, clearly defined purposes. We do not use your data in ways that you would not reasonably expect.</p>
        <h3 style={{ fontSize: '1.15rem', color: '#f1f5f9', marginTop: '1.5rem' }}>3.1 To Operate the Platform</h3>
        <p>Your account data, profile data, and activity data are necessary to create and maintain your account, display your profile to other users, deliver your feed, process connection requests, and enable every core feature of Mericet.</p>
        <h3 style={{ fontSize: '1.15rem', color: '#f1f5f9', marginTop: '1.5rem' }}>3.2 To Personalize Your Experience</h3>
        <p>We use your stated interests, activity patterns, Focus Mode goals, and interaction history to personalize your content feed, suggest relevant connections, surface Collaboration Board opportunities that match your needs, and generate the AI Digest briefing. This personalization is what makes Mericet valuable — and it is always based on your data, never sold to advertisers.</p>
        <h3 style={{ fontSize: '1.15rem', color: '#f1f5f9', marginTop: '1.5rem' }}>3.3 To Power AI Features</h3>
        <p>Our AI systems use your activity data to auto-tag saved content in your Vault, generate bio improvement suggestions, summarize trending content into Collective Intelligence posts, categorize your notifications into Urgent and Digest zones, and process your daily Focus Mode intent. AI processing is performed only on your non-private data. Your encrypted messages are never processed by any AI system.</p>
        <h3 style={{ fontSize: '1.15rem', color: '#f1f5f9', marginTop: '1.5rem' }}>3.4 For Identity and Trust Verification</h3>
        <p>Verification document data is used solely to determine whether your account qualifies for a verified badge. This data is reviewed securely, stored with enhanced encryption, and is never shared with other users, third parties, or advertisers.</p>
        <h3 style={{ fontSize: '1.15rem', color: '#f1f5f9', marginTop: '1.5rem' }}>3.5 For Platform Security</h3>
        <p>We use technical data, login patterns, and behavioral signals to detect fraud, identify suspicious account activity, enforce our Terms of Service, prevent abuse, and protect the safety of all users. This includes our automated logout system for suspicious logins.</p>
        <h3 style={{ fontSize: '1.15rem', color: '#f1f5f9', marginTop: '1.5rem' }}>3.6 For Communication</h3>
        <p>We use your email address and phone number (if provided) to send you OTP codes for login, account security alerts, platform update notifications, and — if you opt in — periodic newsletters or product updates from Puteware. You can unsubscribe from non-essential communications at any time.</p>
        <h3 style={{ fontSize: '1.15rem', color: '#f1f5f9', marginTop: '1.5rem' }}>3.7 For Legal and Compliance Purposes</h3>
        <p>We may use or retain your data as required to comply with applicable Indian laws, respond to lawful government requests, enforce our Terms of Service, and protect the legal rights of Puteware and its users.</p>

        <h2 style={{ fontSize: '1.5rem', marginTop: '2.5rem', color: '#ffffff', borderBottom: '1px solid #1e293b', paddingBottom: '0.5rem' }}>4. What We Never Do With Your Data</h2>
        <p>We want to be explicitly clear about the boundaries of how we use your data:</p>
        <ul style={{ paddingLeft: '20px' }}>
          <li>We do not sell your personal data to any third party, ever.</li>
          <li>We do not allow advertisers to target you based on your Mericet activity, profile, or behavior.</li>
          <li>We do not read your private messages. Ever.</li>
          <li>We do not share your verification documents with other users or external businesses.</li>
          <li>We do not use your data to build profiles for sale to data brokers.</li>
          <li>We do not track your behavior across third-party websites or apps outside of Mericet.</li>
        </ul>
        <p>Mericet is a platform that respects your time and your data. These are not just policies — they are commitments that are architecturally built into how Mericet works.</p>

        <h2 style={{ fontSize: '1.5rem', marginTop: '2.5rem', color: '#ffffff', borderBottom: '1px solid #1e293b', paddingBottom: '0.5rem' }}>5. Data Sharing and Disclosure</h2>
        <p>We share your data only in the following specific and limited circumstances:</p>
        <h3 style={{ fontSize: '1.15rem', color: '#f1f5f9', marginTop: '1.5rem' }}>5.1 Service Providers</h3>
        <p>We work with a small number of trusted third-party service providers who help us operate the platform, including cloud hosting services, email delivery providers, analytics tools, and security monitoring systems. These providers process data on our behalf under strict confidentiality agreements and data processing contracts. They are not permitted to use your data for their own purposes.</p>
        <h3 style={{ fontSize: '1.15rem', color: '#f1f5f9', marginTop: '1.5rem' }}>5.2 Public Profile Information</h3>
        <p>Information you choose to make public — such as your posts, public profile, public Vault folders, and professional headline — is visible to other Mericet users in accordance with your chosen visibility settings. You control what is public and what is not.</p>
        <h3 style={{ fontSize: '1.15rem', color: '#f1f5f9', marginTop: '1.5rem' }}>5.3 Collaboration Board Interactions</h3>
        <p>If you apply for an opportunity listed on the Verified Collaboration Board or if an authorized business awards you an achievement badge, that business may see your public profile as part of the interaction. They do not receive any private data, messages, or verification documents.</p>
        <h3 style={{ fontSize: '1.15rem', color: '#f1f5f9', marginTop: '1.5rem' }}>5.4 Legal Requirements</h3>
        <p>We may disclose your data if required to do so by law, court order, or government directive, or if we believe in good faith that such disclosure is necessary to protect the safety, rights, or property of Puteware, its users, or the public. Where legally permitted, we will notify you before complying with such requests.</p>
        <h3 style={{ fontSize: '1.15rem', color: '#f1f5f9', marginTop: '1.5rem' }}>5.5 Business Transfers</h3>
        <p>In the event of a merger, acquisition, restructuring, or sale of all or part of Puteware's business, your data may be transferred as part of that transaction. We will notify you via email and in-app notification at least 30 days before such a transfer and give you the option to delete your account if you do not consent.</p>
        <h3 style={{ fontSize: '1.15rem', color: '#f1f5f9', marginTop: '1.5rem' }}>5.6 With Your Explicit Consent</h3>
        <p>We may share your data with third parties in ways not described above if we obtain your explicit consent at the time of sharing.</p>

        <h2 style={{ fontSize: '1.5rem', marginTop: '2.5rem', color: '#ffffff', borderBottom: '1px solid #1e293b', paddingBottom: '0.5rem' }}>6. Data Retention</h2>
        <p>We retain your data for as long as your account is active and as long as necessary to provide you with the platform's services. The following retention principles apply:</p>
        <ul style={{ paddingLeft: '20px' }}>
          <li>Active account data is retained for the lifetime of your account.</li>
          <li>If you delete your account, your public profile and posts are removed within 24 to 48 hours. Full deletion from all backup systems is completed within 30 days.</li>
          <li>Verification documents are retained for up to 12 months after your account closes for fraud prevention and legal compliance purposes, after which they are permanently destroyed.</li>
          <li>Communication metadata (not content) may be retained for up to 6 months for security and abuse prevention.</li>
          <li>Data required to comply with legal obligations may be retained for longer periods as mandated by applicable law.</li>
        </ul>

        <h2 style={{ fontSize: '1.5rem', marginTop: '2.5rem', color: '#ffffff', borderBottom: '1px solid #1e293b', paddingBottom: '0.5rem' }}>7. Data Security</h2>
        <p>The security of your data is a core engineering priority at Puteware, not an afterthought.</p>
        <h3 style={{ fontSize: '1.15rem', color: '#f1f5f9', marginTop: '1.5rem' }}>7.1 Encryption</h3>
        <p>All data transmitted between your device and Mericet's servers is encrypted using HTTPS/TLS. All private messages are end-to-end encrypted, which means they are unreadable to anyone except the sender and recipient — including Puteware. Verification documents and sensitive identity data are stored with additional layers of encryption at rest.</p>
        <h3 style={{ fontSize: '1.15rem', color: '#f1f5f9', marginTop: '1.5rem' }}>7.2 Access Controls</h3>
        <p>Internal access to user data is strictly limited to team members who need it for their specific role. Access to sensitive categories of data, such as verification documents, is controlled with multi-factor authentication, audit logs, and role-based permissions.</p>
        <h3 style={{ fontSize: '1.15rem', color: '#f1f5f9', marginTop: '1.5rem' }}>7.3 Security Monitoring</h3>
        <p>Mericet continuously monitors for suspicious login activity, unauthorized access attempts, and unusual behavioral patterns. Our automated security system will force-logout any session that appears to be compromised and notify you immediately.</p>
        <h3 style={{ fontSize: '1.15rem', color: '#f1f5f9', marginTop: '1.5rem' }}>7.4 Vulnerability Management</h3>
        <p>We conduct regular security audits and respond to responsible vulnerability disclosures from the security community. If you discover a security vulnerability, please report it to security@puteware.com rather than disclosing it publicly.</p>
        <h3 style={{ fontSize: '1.15rem', color: '#f1f5f9', marginTop: '1.5rem' }}>7.5 Breach Notification</h3>
        <p>In the unlikely event of a data breach that affects your personal data, Puteware will notify you within 72 hours of becoming aware of the breach, as required under applicable data protection law. We will inform you of the nature of the breach, the data affected, and the steps we are taking to address it.</p>

        <h2 style={{ fontSize: '1.5rem', marginTop: '2.5rem', color: '#ffffff', borderBottom: '1px solid #1e293b', paddingBottom: '0.5rem' }}>8. Your Rights Over Your Data</h2>
        <p>You have strong rights over your personal data on Mericet. We have designed the platform to make it easy to exercise these rights without friction.</p>
        <ul style={{ paddingLeft: '20px' }}>
          <li><strong>Right to Access:</strong> You can request a complete copy of all personal data we hold about you at any time by emailing privacy@puteware.com. We will provide this within 30 days.</li>
          <li><strong>Right to Correction:</strong> You can update or correct your personal information directly from your Profile and Settings at any time. If you believe we hold inaccurate data about you that you cannot correct yourself, contact us and we will correct it promptly.</li>
          <li><strong>Right to Deletion:</strong> You have the right to request the permanent deletion of your account and all associated personal data. You can initiate this from Settings or by emailing us. Full deletion is completed within 30 days, except for data we are legally required to retain.</li>
          <li><strong>Right to Data Portability:</strong> You may request an export of your personal data in a machine-readable format (JSON or CSV), including your posts, saved Vault content, connection list, and profile data.</li>
          <li><strong>Right to Restrict Processing:</strong> You can request that we restrict certain categories of data processing, such as disabling AI personalization, opting out of the Focus Mode intent system, or turning off Digest summary generation. These can be managed from your Settings panel.</li>
          <li><strong>Right to Withdraw Consent:</strong> Where our data processing is based on your consent, you may withdraw that consent at any time. Withdrawal of consent does not affect the lawfulness of processing conducted before withdrawal.</li>
        </ul>
        <p>To exercise any of the rights above, contact privacy@puteware.com. We do not charge fees for data requests. We respond to all requests within 30 calendar days. For complex or multiple simultaneous requests, we may extend this by an additional 30 days and will inform you accordingly.</p>

        <h2 style={{ fontSize: '1.5rem', marginTop: '2.5rem', color: '#ffffff', borderBottom: '1px solid #1e293b', paddingBottom: '0.5rem' }}>9. Cookies and Tracking Technologies</h2>
        <h3 style={{ fontSize: '1.15rem', color: '#f1f5f9', marginTop: '1.5rem' }}>9.1 What Are Cookies</h3>
        <p>Cookies are small text files stored on your device when you visit a website or use an app. Mericet uses cookies and similar technologies in a strictly limited manner.</p>
        <h3 style={{ fontSize: '1.15rem', color: '#f1f5f9', marginTop: '1.5rem' }}>9.2 Essential Cookies</h3>
        <p>These cookies are necessary for the platform to function. They maintain your login session, remember your theme preference (Light or Dark Mode), and store your basic settings. These cannot be disabled without breaking core functionality.</p>
        <h3 style={{ fontSize: '1.15rem', color: '#f1f5f9', marginTop: '1.5rem' }}>9.3 Preference Cookies</h3>
        <p>These cookies remember your notification preferences, Focus Mode settings, muted accounts, and other personalized configurations so you do not have to reset them every time you log in.</p>
        <h3 style={{ fontSize: '1.15rem', color: '#f1f5f9', marginTop: '1.5rem' }}>9.4 Analytics Cookies</h3>
        <p>We use anonymized, aggregated analytics to understand how different features are used across the platform. This helps us prioritize improvements. We do not use analytics that can identify individual users or their specific behaviors.</p>
        <h3 style={{ fontSize: '1.15rem', color: '#f1f5f9', marginTop: '1.5rem' }}>9.5 No Advertising Cookies</h3>
        <p>Mericet does not use advertising cookies, cross-site tracking cookies, or behavioral tracking technologies of any kind. We do not share your browsing behavior with advertising networks.</p>
        <h3 style={{ fontSize: '1.15rem', color: '#f1f5f9', marginTop: '1.5rem' }}>9.6 Managing Cookies</h3>
        <p>You can manage or delete cookies through your browser settings or your Mericet Settings panel at any time. Note that disabling essential cookies may affect platform functionality.</p>

        <h2 style={{ fontSize: '1.5rem', marginTop: '2.5rem', color: '#ffffff', borderBottom: '1px solid #1e293b', paddingBottom: '0.5rem' }}>10. Children's Privacy</h2>
        <p>Mericet is not intended for use by children under the age of 16. We do not knowingly collect personal data from children. If we become aware that an account has been created by someone under 16 without verified parental consent, we will immediately suspend the account and delete the associated data. If you believe a child under 16 is using Mericet without parental consent, please contact us at privacy@puteware.com.</p>

        <h2 style={{ fontSize: '1.5rem', marginTop: '2.5rem', color: '#ffffff', borderBottom: '1px solid #1e293b', paddingBottom: '0.5rem' }}>11. International Users</h2>
        <p>Mericet is based in India and operated under Indian law, including the Digital Personal Data Protection Act, 2023 (DPDP Act). If you are accessing Mericet from outside India, your personal data will be processed in India. By using the platform, you consent to the transfer and processing of your data in India in accordance with this Privacy Policy.</p>

        <h2 style={{ fontSize: '1.5rem', marginTop: '2.5rem', color: '#ffffff', borderBottom: '1px solid #1e293b', paddingBottom: '0.5rem' }}>12. Changes to This Privacy Policy</h2>
        <p>Puteware may update this Privacy Policy as the platform evolves, as our practices change, or as required by applicable law. We will notify you of any material changes via in-app notification and email at least 14 days before the changes take effect. The "Last Updated" date at the top of this document will always reflect the most recent version. We encourage you to review this Policy periodically.</p>

        <h2 style={{ fontSize: '1.5rem', marginTop: '2.5rem', color: '#ffffff', borderBottom: '1px solid #1e293b', paddingBottom: '0.5rem' }}>13. Contact Us</h2>
        <p>For all privacy-related questions, data requests, or concerns:</p>
        <ul style={{ paddingLeft: '20px' }}>
          <li><strong>Privacy Team:</strong> privacy@puteware.com</li>
          <li><strong>Legal Team:</strong> legal@puteware.com</li>
          <li><strong>Security Reports:</strong> security@puteware.com</li>
        </ul>
        <p>Response Time: Within 30 calendar days for all general inquiries; within 72 hours for security-related concerns. If you are not satisfied with how we have handled your concern, you have the right to escalate your complaint to the appropriate data protection authority under Indian law.</p>
      </div>
    </div>
  );
}